language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-basic-webapp' ]; then cd .. && eval "mv $currentfolder generator-basic-webapp" && cd generator-basic-webapp; fi

